#!/usr/bin/env bash
# display the econtent of the best school and say "hi"
i=1
while [ $i -le 10 ]; do
  if [ $i -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
