#!/usr/bin/env bash
# writing a bash script that displays the time for hours and minutes
hours=o
while [ $Hours -le 12 ]; do
 echo "Hour: $hours"
 minute=1
 while [ $minute -le 59 ]; do
  echo "Minute: $minute"
  ((minute++))
 done
 ((hours++))
done
