#!/usr/bin/env bash
# displaying the PID along with the name
for pid in /proc/[0-9]*; do
    cmd=$(cat "$pid/comm" 2>/dev/null)
    if [[ "$cmd" == *bash* ]]; then
        echo "$(basename "$pid") $cmd"
    fi
done
